name: Format and check broken links
run-name: We are verifying that everything is in order 🚀

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main
        with:
          install-command: cd website && yarn install --frozen-lockfile
  
  check-formatting:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: OffchainLabs/actions/node-modules/restore@main

      - name: Check formatting with Prettier
        working-directory: ./website
        run: yarn format:check