name: Format and check broken links
run-name: We are verifying that everything is in order 🚀

on:
  pull_request:
    branches:
      - master

jobs:
  check-formatting:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install node_modules
        working-directory: ./website
        run: yarn install

      - name: Check formatting with Prettier
        working-directory: ./website
        run: yarn format:check